# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    end
    
    config.vm.define "sonobouy_default" do |sonobouy_default|
    sonobouy_default.vm.box = "Kiowa/kubean-e2e-vm-template"
    sonobouy_default.vm.box_version = "0"
    sonobouy_default.vm.network "public_network", ip: "sonobouy_default_ip", bridge: "ens192"
    sonobouy_default.vm.hostname="sonobouy_default"
    end
    
    config.vm.define "sonobouy_default2" do |sonobouy_default2|
    sonobouy_default2.vm.box = "Kiowa/kubean-e2e-vm-template"
    sonobouy_default2.vm.box_version = "0"
    sonobouy_default2.vm.network "public_network", ip: "sonobouy_default2_ip", bridge: "ens192"
    sonobouy_default2.vm.hostname="sonobouy_default2"
    end
    
end