name: main

on:
  push:
    branches:
      - master

env:
  KUKEAN_OPERATOR_IMAGE_NAME: kubean-operator
  KUBESPRAY_IMAGE_NAME: kubespray
  SPRAY_JOB_IMAGE_NAME: spray-job
  KUBESPRAY_TAG: master
jobs:
  e2e:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: e2e
        run: |
          #bash hack/e2e.sh "v0.2.2" "v0.2.2" "https://kubean-io.github.io/kubean-helm-chart/" "ghcr.io/kubean-io" "v0.2.2" ${{ runner.name }}
          echo "hello"
  sonobouy_e2e:
    needs: e2e
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.2

      - name: e2e
        run: |
          bash hack/sonobouy_e2e.sh "v0.2.2" "v0.2.2" "https://kubean-io.github.io/kubean-helm-chart/" "ghcr.io/kubean-io" "v0.2.2" ${{ runner.name }}
          #echo "hello"
